services:
  php-apache:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    container_name: php-local-dev
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1234" 
      MYSQL_DATABASE: idk_ambiente_web 
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db_data: